#!/usr/bin/env python3
"""
Database Symbol Manager

This script provides direct database operations for managing trading symbols
using the SymbolManager class. It's focused on CRUD operations for symbols
in the database, separate from the high-level configuration management.
"""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent.parent))

from src.data.sources.symbol_manager import SymbolManager


def add_sample_symbols(symbol_manager):
    """Add some sample trading symbols."""
    # Add some major tech stocks
    symbols = [
        # ("AAPL", "Apple Inc."),
        # ("MSFT", "Microsoft Corporation"),
        # ("GOOGL", "Alphabet Inc."),
        # ("AMZN", "Amazon.com Inc."),
        # ("META", "Meta Platforms Inc."),
        # ("PTPI", "Petros Pharmaceuticals Inc."),
        ("AAPL", "Apple Inc."),
        ("MSFT", "Microsoft Corporation"),
        ("GOOGL", "Alphabet Inc."),
        ("AMZN", "Amazon.com, Inc."),
        ("META", "Meta Platforms, Inc."),
        ("PDFS", "PDF Solutions, Inc."),
        ("ROG", "Rogers Corporation"),
        ("AA", "Alcoa Corporation"),
        ("AAL", "American Airlines Group, Inc."),
        ("AAON", "AAON, Inc."),
        ("AAP", "Advance Auto Parts Inc."),
        ("ABBV", "AbbVie Inc."),
        ("ABNB", "Airbnb, Inc."),
        ("ABT", "Abbott Laboratories"),
        ("ACGL", "Arch Capital Group Ltd."),
        ("ACHC", "Acadia Healthcare Company, Inc."),
        ("ACI", "Albertsons Companies, Inc."),
        ("ACIW", "ACI Worldwide, Inc."),
        ("ACLS", "Axcelis Technologies, Inc."),
        ("ACM", "AECOM"),
        ("ACN", "Accenture plc"),
        ("ADBE", "Adobe Inc."),
        ("ADC", "Agree Realty Corporation"),
        ("ADEA", "Adeia Inc."),
        ("ADI", "Analog Devices, Inc."),
        ("ADM", "Archer-Daniels-Midland Company"),
        ("ADP", "Automatic Data Processing, Inc."),
        ("ADSK", "Autodesk, Inc."),
        ("ADT", "ADT Inc."),
        ("AEE", "Ameren Corporation"),
        ("AEIS", "Advanced Energy Industries, Inc"),
        ("AEP", "American Electric Power Company"),
        ("AES", "The AES Corporation"),
        ("AFG", "American Financial Group, Inc."),
        ("AFL", "AFLAC Incorporated"),
        ("AFRM", "Affirm Holdings, Inc."),
        ("AGCO", "AGCO Corporation"),
        ("AGNC", "AGNC Investment Corp."),
        ("AGO", "Assured Guaranty Ltd."),
        ("AGYS", "Agilysys, Inc."),
        ("AIG", "American International Group, I"),
        ("AIZ", "Assurant, Inc."),
        ("AJG", "Arthur J. Gallagher & Co."),
        ("AKAM", "Akamai Technologies, Inc."),
        ("AL", "Air Lease Corporation"),
        ("ALAB", "Astera Labs, Inc."),
        ("ALB", "Albemarle Corporation"),
        ("ALGM", "Allegro MicroSystems, Inc."),
        ("ALGN", "Align Technology, Inc."),
        ("ALK", "Alaska Air Group, Inc."),
        ("ALL", "Allstate Corporation (The)"),
        ("ALLE", "Allegion plc"),
        ("ALLY", "Ally Financial Inc."),
        ("ALNY", "Alnylam Pharmaceuticals, Inc."),
        ("ALSN", "Allison Transmission Holdings, "),
        ("ALTR", "Altair Engineering Inc."),
        ("AM", "Antero Midstream Corporation"),
        ("AMAT", "Applied Materials, Inc."),
        ("AMCR", "Amcor plc"),
        ("AMD", "Advanced Micro Devices, Inc."),
        ("AME", "AMETEK, Inc."),
        ("AMED", "Amedisys Inc"),
        ("AMG", "Affiliated Managers Group, Inc."),
        ("AMGN", "Amgen Inc."),
        ("AMH", "American Homes 4 Rent"),
        ("AMKR", "Amkor Technology, Inc."),
        ("AMP", "Ameriprise Financial, Inc."),
        ("AMT", "American Tower Corporation (REI"),
        ("AMTM", "Amentum Holdings, Inc."),
        ("AN", "AutoNation, Inc."),
        ("ANET", "Arista Networks, Inc."),
        ("ANSS", "ANSYS, Inc."),
        ("AON", "Aon plc"),
        ("AOS", "A.O. Smith Corporation"),
        ("AOSL", "Alpha and Omega Semiconductor L"),
        ("APA", "APA Corporation"),
        ("APD", "Air Products and Chemicals, Inc"),
        ("APG", "APi Group Corporation"),
        ("APH", "Amphenol Corporation"),
        ("APLS", "Apellis Pharmaceuticals, Inc."),
        ("APO", "Apollo Global Management, Inc. "),
        ("APP", "Applovin Corporation"),
        ("APPF", "AppFolio, Inc."),
        ("APTV", "Aptiv PLC"),
        ("AR", "Antero Resources Corporation"),
        ("ARE", "Alexandria Real Estate Equities"),
        ("ARES", "Ares Management Corporation"),
        ("ARLO", "Arlo Technologies, Inc."),
        ("ARMK", "Aramark"),
        ("ARW", "Arrow Electronics, Inc."),
        ("AS", "Amer Sports, Inc."),
        ("ASGN", "ASGN Incorporated"),
        ("ASH", "Ashland Inc."),
        ("ATEN", "A10 Networks, Inc."),
        ("ATI", "ATI Inc."),
        ("ATO", "Atmos Energy Corporation"),
        ("ATR", "AptarGroup, Inc."),
        ("AVB", "AvalonBay Communities, Inc."),
        ("AVGO", "Broadcom Inc."),
        ("AVT", "Avnet, Inc."),
        ("AVTR", "Avantor, Inc."),
        ("AVY", "Avery Dennison Corporation"),
        ("AWI", "Armstrong World Industries Inc"),
        ("AWK", "American Water Works Company, I"),
        ("AXON", "Axon Enterprise, Inc."),
        ("AXP", "American Express Company"),
        ("AXS", "Axis Capital Holdings Limited"),
        ("AXTA", "Axalta Coating Systems Ltd."),
        ("AYI", "Acuity Inc."),
        ("AZEK", "The AZEK Company Inc."),
        ("AZO", "AutoZone, Inc."),
        ("AZTA", "Azenta, Inc."),
        ("BA", "Boeing Company (The)"),
        ("BAC", "Bank of America Corporation"),
        ("BAH", "Booz Allen Hamilton Holding Cor"),
        ("BALL", "Ball Corporation"),
        ("BAX", "Baxter International Inc."),
        ("BBWI", "Bath & Body Works, Inc."),
        ("BBY", "Best Buy Co., Inc."),
        ("BC", "Brunswick Corporation"),
        ("BDC", "Belden Inc"),
        ("BDX", "Becton, Dickinson and Company"),
        ("BEN", "Franklin Resources, Inc."),
        ("BEPC", "Brookfield Renewable Corporatio"),
        ("BERY", "Berry Global Group, Inc."),
        ("BFAM", "Bright Horizons Family Solution"),
        ("BG", "Bunge Limited"),
        ("BHE", "Benchmark Electronics, Inc."),
        ("BHF", "Brighthouse Financial, Inc."),
        ("BIIB", "Biogen Inc."),
        ("BILL", "BILL Holdings, Inc."),
        ("BIO", "Bio-Rad Laboratories, Inc."),
        ("BIRK", "Birkenstock Holding plc"),
        ("BJ", "BJ's Wholesale Club Holdings, I"),
        ("BK", "The Bank of New York Mellon Cor"),
        ("BKNG", "Booking Holdings Inc. Common St"),
        ("BKR", "Baker Hughes Company"),
        ("BL", "BlackLine, Inc."),
        ("BLD", "TopBuild Corp."),
        ("BLDR", "Builders FirstSource, Inc."),
        ("BLK", "BlackRock, Inc."),
        ("BLKB", "Blackbaud, Inc."),
        ("BMI", "Badger Meter, Inc."),
        ("BMRN", "BioMarin Pharmaceutical Inc."),
        ("BMY", "Bristol-Myers Squibb Company"),
        ("BOKF", "BOK Financial Corporation"),
        ("BOX", "Box, Inc."),
        ("BPOP", "Popular, Inc."),
        ("BR", "Broadridge Financial Solutions,"),
        ("BRBR", "BellRing Brands, Inc."),
        ("BRKR", "Bruker Corporation"),
        ("BRO", "Brown & Brown, Inc."),
        ("BROS", "Dutch Bros Inc."),
        ("BRX", "Brixmor Property Group Inc."),
        ("BSX", "Boston Scientific Corporation"),
        ("BSY", "Bentley Systems, Incorporated"),
        ("BURL", "Burlington Stores, Inc."),
        ("BWA", "BorgWarner Inc."),
        ("BWXT", "BWX Technologies, Inc."),
        ("BX", "Blackstone Inc."),
        ("BXP", "BXP, Inc."),
        ("BYD", "Boyd Gaming Corporation"),
        ("C", "Citigroup, Inc."),
        ("CACC", "Credit Acceptance Corporation"),
        ("CACI", "CACI International, Inc."),
        ("CAG", "ConAgra Brands, Inc."),
        ("CAH", "Cardinal Health, Inc."),
        ("CALX", "Calix, Inc"),
        ("CAR", "Avis Budget Group, Inc."),
        ("CARR", "Carrier Global Corporation"),
        ("CART", "Maplebear Inc."),
        ("CASY", "Caseys General Stores, Inc."),
        ("CAT", "Caterpillar, Inc."),
        ("CAVA", "CAVA Group, Inc."),
        ("CB", "Chubb Limited"),
        ("CBOE", "Cboe Global Markets, Inc."),
        ("CBRE", "CBRE Group Inc"),
        ("CBSH", "Commerce Bancshares, Inc."),
        ("CC", "Chemours Company (The)"),
        ("CCCS", "CCC Intelligent Solutions Holdi"),
        ("CCI", "Crown Castle Inc."),
        ("CCK", "Crown Holdings, Inc."),
        ("CCL", "Carnival Corporation"),
        ("CDNS", "Cadence Design Systems, Inc."),
        ("CDW", "CDW Corporation"),
        ("CE", "Celanese Corporation"),
        ("CEG", "Constellation Energy Corporatio"),
        ("CELH", "Celsius Holdings, Inc."),
        ("CERT", "Certara, Inc."),
        ("CEVA", "CEVA, Inc."),
        ("CF", "CF Industries Holdings, Inc."),
        ("CFG", "Citizens Financial Group, Inc."),
        ("CFLT", "Confluent, Inc."),
        ("CFR", "Cullen/Frost Bankers, Inc."),
        ("CG", "The Carlyle Group Inc."),
        ("CGNX", "Cognex Corporation"),
        ("CHD", "Church & Dwight Company, Inc."),
        ("CHDN", "Churchill Downs, Incorporated"),
        ("CHE", "Chemed Corp"),
        ("CHH", "Choice Hotels International, In"),
        ("CHRD", "Chord Energy Corporation"),
        ("CHRW", "C.H. Robinson Worldwide, Inc."),
        ("CHTR", "Charter Communications, Inc."),
        ("CI", "The Cigna Group"),
        ("CIEN", "Ciena Corporation"),
        ("CINF", "Cincinnati Financial Corporatio"),
        ("CIVI", "Civitas Resources, Inc."),
        ("CL", "Colgate-Palmolive Company"),
        ("CLF", "Cleveland-Cliffs Inc."),
        ("CLH", "Clean Harbors, Inc."),
        ("CLVT", "Clarivate Plc"),
        ("CLX", "Clorox Company (The)"),
        ("CMA", "Comerica Incorporated"),
        ("CMCSA", "Comcast Corporation"),
        ("CME", "CME Group Inc."),
        ("CMG", "Chipotle Mexican Grill, Inc."),
        ("CMI", "Cummins Inc."),
        ("CMS", "CMS Energy Corporation"),
        ("CNA", "CNA Financial Corporation"),
        ("CNC", "Centene Corporation"),
        ("CNH", "CNH Industrial N.V."),
        ("CNM", "Core & Main, Inc."),
        ("CNP", "CenterPoint Energy, Inc (Holdin"),
        ("CNXC", "Concentrix Corporation"),
        ("CNXN", "PC Connection, Inc."),
        ("COF", "Capital One Financial Corporati"),
        ("COHR", "Coherent Corp."),
        ("COHU", "Cohu, Inc."),
        ("COIN", "Coinbase Global, Inc."),
        ("COKE", "Coca-Cola Consolidated, Inc."),
        ("COLB", "Columbia Banking System, Inc."),
        ("COLD", "Americold Realty Trust, Inc."),
        ("COLM", "Columbia Sportswear Company"),
        ("COO", "The Cooper Companies, Inc."),
        ("COP", "ConocoPhillips"),
        ("COR", "Cencora, Inc."),
        ("COST", "Costco Wholesale Corporation"),
        ("COTY", "Coty Inc."),
        ("CPAY", "Corpay, Inc."),
        ("CPB", "The Campbell's Company"),
        ("CPNG", "Coupang, Inc."),
        ("CPRI", "Capri Holdings Limited"),
        ("CPRT", "Copart, Inc."),
        ("CPT", "Camden Property Trust"),
        ("CR", "Crane Company"),
        ("CRH", "CRH PLC"),
        ("CRI", "Carter's, Inc."),
        ("CRL", "Charles River Laboratories Inte"),
        ("CRM", "Salesforce, Inc."),
        ("CROX", "Crocs, Inc."),
        ("CRSR", "Corsair Gaming, Inc."),
        ("CRUS", "Cirrus Logic, Inc."),
        ("CRWD", "CrowdStrike Holdings, Inc."),
        ("CSCO", "Cisco Systems, Inc."),
        ("CSGP", "CoStar Group, Inc."),
        ("CSL", "Carlisle Companies Incorporated"),
        ("CSX", "CSX Corporation"),
        ("CTAS", "Cintas Corporation"),
        ("CTRA", "Coterra Energy Inc."),
        ("CTS", "CTS Corporation"),
        ("CTSH", "Cognizant Technology Solutions "),
        ("CTVA", "Corteva, Inc."),
        ("CUBE", "CubeSmart"),
        ("CUZ", "Cousins Properties Incorporated"),
        ("CVLT", "Commvault Systems, Inc."),
        ("CVNA", "Carvana Co."),
        ("CVS", "CVS Health Corporation"),
        ("CVX", "Chevron Corporation"),
        ("CW", "Curtiss-Wright Corporation"),
        ("CWEN", "Clearway Energy, Inc."),
        ("CXM", "Sprinklr, Inc."),
        ("CXT", "Crane NXT, Co."),
        ("CZR", "Caesars Entertainment, Inc."),
        ("D", "Dominion Energy, Inc."),
        ("DAL", "Delta Air Lines, Inc."),
        ("DAR", "Darling Ingredients Inc."),
        ("DASH", "DoorDash, Inc."),
        ("DAY", "Dayforce, Inc."),
        ("DBX", "Dropbox, Inc."),
        ("DCI", "Donaldson Company, Inc."),
        ("DD", "DuPont de Nemours, Inc."),
        ("DDOG", "Datadog, Inc."),
        ("DDS", "Dillard's, Inc."),
        ("DE", "Deere & Company"),
        ("DECK", "Deckers Outdoor Corporation"),
        ("DELL", "Dell Technologies Inc."),
        ("DFS", "Discover Financial Services"),
        ("DG", "Dollar General Corporation"),
        ("DGII", "Digi International Inc."),
        ("DGX", "Quest Diagnostics Incorporated"),
        ("DHI", "D.R. Horton, Inc."),
        ("DHR", "Danaher Corporation"),
        ("DINO", "HF Sinclair Corporation"),
        ("DIOD", "Diodes Incorporated"),
        ("DIS", "Walt Disney Company (The)"),
        ("DJT", "Trump Media & Technology Group "),
        ("DKNG", "DraftKings Inc."),
        ("DKS", "Dick's Sporting Goods Inc"),
        ("DLB", "Dolby Laboratories"),
        ("DLR", "Digital Realty Trust, Inc."),
        ("DLTR", "Dollar Tree, Inc."),
        ("DNB", "Dun & Bradstreet Holdings, Inc."),
        ("DOC", "Healthpeak Properties, Inc."),
        ("DOCN", "DigitalOcean Holdings, Inc."),
        ("DOCS", "Doximity, Inc."),
        ("DOCU", "DocuSign, Inc."),
        ("DOV", "Dover Corporation"),
        ("DOW", "Dow Inc."),
        ("DOX", "Amdocs Limited"),
        ("DPZ", "Domino's Pizza Inc"),
        ("DRI", "Darden Restaurants, Inc."),
        ("DT", "Dynatrace, Inc."),
        ("DTE", "DTE Energy Company"),
        ("DTM", "DT Midstream, Inc."),
        ("DUK", "Duke Energy Corporation (Holdin"),
        ("DUOL", "Duolingo, Inc."),
        ("DV", "DoubleVerify Holdings, Inc."),
        ("DVA", "DaVita Inc."),
        ("DVN", "Devon Energy Corporation"),
        ("DXC", "DXC Technology Company"),
        ("DXCM", "DexCom, Inc."),
        ("EA", "Electronic Arts Inc."),
        ("EBAY", "eBay Inc."),
        ("ECG", "Everus Construction Group, Inc."),
        ("ECL", "Ecolab Inc."),
        ("ED", "Consolidated Edison, Inc."),
        ("EEFT", "Euronet Worldwide, Inc."),
        ("EFX", "Equifax, Inc."),
        ("EG", "Everest Group, Ltd."),
        ("EGP", "EastGroup Properties, Inc."),
        ("EHC", "Encompass Health Corporation"),
        ("EIX", "Edison International"),
        ("EL", "Estee Lauder Companies, Inc. (T"),
        ("ELAN", "Elanco Animal Health Incorporat"),
        ("ELF", "e.l.f. Beauty, Inc."),
        ("ELS", "Equity Lifestyle Properties, In"),
        ("ELV", "Elevance Health, Inc."),
        ("EME", "EMCOR Group, Inc."),
        ("EMN", "Eastman Chemical Company"),
        ("EMR", "Emerson Electric Company"),
        ("ENOV", "Enovis Corporation"),
        ("ENPH", "Enphase Energy, Inc."),
        ("ENTG", "Entegris, Inc."),
        ("EOG", "EOG Resources, Inc."),
        ("EPAM", "EPAM Systems, Inc."),
        ("EPR", "EPR Properties"),
        ("EQH", "Equitable Holdings, Inc."),
        ("EQIX", "Equinix, Inc."),
        ("EQR", "Equity Residential"),
        ("EQT", "EQT Corporation"),
        ("ES", "Eversource Energy (D/B/A)"),
        ("ESAB", "ESAB Corporation"),
        ("ESI", "Element Solutions Inc."),
        ("ESS", "Essex Property Trust, Inc."),
        ("ESTC", "Elastic N.V."),
        ("ETN", "Eaton Corporation, PLC"),
        ("ETR", "Entergy Corporation"),
        ("ETSY", "Etsy, Inc."),
        ("EVR", "Evercore Inc."),
        ("EVRG", "Evergy, Inc."),
        ("EW", "Edwards Lifesciences Corporatio"),
        ("EWBC", "East West Bancorp, Inc."),
        ("EXAS", "Exact Sciences Corporation"),
        ("EXC", "Exelon Corporation"),
        ("EXE", "Expand Energy Corporation"),
        ("EXEL", "Exelixis, Inc."),
        ("EXP", "Eagle Materials Inc"),
        ("EXPD", "Expeditors International of Was"),
        ("EXPE", "Expedia Group, Inc."),
        ("EXR", "Extra Space Storage Inc"),
        ("EXTR", "Extreme Networks, Inc."),
        ("F", "Ford Motor Company"),
        ("FAF", "First American Corporation (New"),
        ("FANG", "Diamondback Energy, Inc."),
        ("FAST", "Fastenal Company"),
        ("FBIN", "Fortune Brands Innovations, Inc"),
        ("FCN", "FTI Consulting, Inc."),
        ("FCNCA", "First Citizens BancShares, Inc."),
        ("FCX", "Freeport-McMoRan, Inc."),
        ("FDS", "FactSet Research Systems Inc."),
        ("FDX", "FedEx Corporation"),
        ("FE", "FirstEnergy Corp."),
        ("FERG", "Ferguson Enterprises Inc."),
        ("FFIV", "F5, Inc."),
        ("FHB", "First Hawaiian, Inc."),
        ("FHN", "First Horizon Corporation"),
        ("FI", "Fiserv, Inc."),
        ("FICO", "Fair Isaac Corporation"),
        ("FIS", "Fidelity National Information S"),
        ("FITB", "Fifth Third Bancorp"),
        ("FIVE", "Five Below, Inc."),
        ("FIVN", "Five9, Inc."),
        ("FIX", "Comfort Systems USA, Inc."),
        ("FLEX", "Flex Ltd."),
        ("FLO", "Flowers Foods, Inc."),
        ("FLS", "Flowserve Corporation"),
        ("FMC", "FMC Corporation"),
        ("FN", "Fabrinet"),
        ("FNB", "F.N.B. Corporation"),
        ("FND", "Floor & Decor Holdings, Inc."),
        ("FNF", "FNF Group of Fidelity National "),
        ("FORM", "FormFactor, Inc."),
        ("FOUR", "Shift4 Payments, Inc."),
        ("FOX", "Fox Corporation"),
        ("FOXA", "Fox Corporation"),
        ("FR", "First Industrial Realty Trust, "),
        ("FRPT", "Freshpet, Inc."),
        ("FRT", "Federal Realty Investment Trust"),
        ("FSLR", "First Solar, Inc."),
        ("FTI", "TechnipFMC plc"),
        ("FTNT", "Fortinet, Inc."),
        ("FTRE", "Fortrea Holdings Inc."),
        ("FTV", "Fortive Corporation"),
        ("FWONA", "Liberty Media Corporation - Ser"),
        ("FWONK", "Liberty Media Corporation - Ser"),
        ("FYBR", "Frontier Communications Parent,"),
        ("G", "Genpact Limited"),
        ("GAP", "Gap, Inc. (The)"),
        ("GD", "General Dynamics Corporation"),
        ("GDDY", "GoDaddy Inc."),
        ("GE", "GE Aerospace"),
        ("GEHC", "GE HealthCare Technologies Inc."),
        ("GEN", "Gen Digital Inc."),
        ("GEV", "GE Vernova Inc."),
        ("GFS", "GlobalFoundries Inc."),
        ("GGG", "Graco Inc."),
        ("GILD", "Gilead Sciences, Inc."),
        ("GIS", "General Mills, Inc."),
        ("GL", "Globe Life Inc."),
        ("GLOB", "Globant S.A."),
        ("GLPI", "Gaming and Leisure Properties, "),
        ("GLW", "Corning Incorporated"),
        ("GM", "General Motors Company"),
        ("GME", "GameStop Corporation"),
        ("GMED", "Globus Medical, Inc."),
        ("GNRC", "Generac Holdlings Inc."),
        ("GNTX", "Gentex Corporation"),
        ("GO", "Grocery Outlet Holding Corp."),
        ("GOOG", "Alphabet Inc."),
        ("GPC", "Genuine Parts Company"),
        ("GPK", "Graphic Packaging Holding Compa"),
        ("GPN", "Global Payments Inc."),
        ("GRAL", "GRAIL, Inc."),
        ("GRMN", "Garmin Ltd."),
        ("GS", "Goldman Sachs Group, Inc. (The)"),
        ("GTES", "Gates Industrial Corporation pl"),
        ("GTLB", "GitLab Inc."),
        ("GWRE", "Guidewire Software, Inc."),
        ("GWW", "W.W. Grainger, Inc."),
        ("GXO", "GXO Logistics, Inc."),
        ("H", "Hyatt Hotels Corporation"),
        ("HAL", "Halliburton Company"),
        ("HAS", "Hasbro, Inc."),
        ("HAYW", "Hayward Holdings, Inc."),
        ("HBAN", "Huntington Bancshares Incorpora"),
        ("HCA", "HCA Healthcare, Inc."),
        ("HD", "Home Depot, Inc. (The)"),
        ("HEI", "Heico Corporation"),
        ("HES", "Hess Corporation"),
        ("HHH", "Howard Hughes Holdings Inc."),
        ("HIG", "The Hartford Insurance Group, I"),
        ("HII", "Huntington Ingalls Industries, "),
        ("HIW", "Highwoods Properties, Inc."),
        ("HLI", "Houlihan Lokey, Inc."),
        ("HLIT", "Harmonic Inc."),
        ("HLT", "Hilton Worldwide Holdings Inc."),
        ("HOG", "Harley-Davidson, Inc."),
        ("HOLX", "Hologic, Inc."),
        ("HON", "Honeywell International Inc."),
        ("HOOD", "Robinhood Markets, Inc."),
        ("HPE", "Hewlett Packard Enterprise Comp"),
        ("HPQ", "HP Inc."),
        ("HR", "Healthcare Realty Trust Incorpo"),
        ("HRB", "H&R Block, Inc."),
        ("HRL", "Hormel Foods Corporation"),
        ("HSIC", "Henry Schein, Inc."),
        ("HST", "Host Hotels & Resorts, Inc."),
        ("HSY", "The Hershey Company"),
        ("HUBB", "Hubbell Inc"),
        ("HUBS", "HubSpot, Inc."),
        ("HUM", "Humana Inc."),
        ("HUN", "Huntsman Corporation"),
        ("HWM", "Howmet Aerospace Inc."),
        ("HXL", "Hexcel Corporation"),
        ("IAC", "IAC Inc."),
        ("IBKR", "Interactive Brokers Group, Inc."),
        ("IBM", "International Business Machines"),
        ("ICE", "Intercontinental Exchange Inc."),
        ("ICHR", "Ichor Holdings"),
        ("IDA", "IDACORP, Inc."),
        ("IDCC", "InterDigital, Inc."),
        ("IDXX", "IDEXX Laboratories, Inc."),
        ("IEX", "IDEX Corporation"),
        ("IFF", "International Flavors & Fragran"),
        ("ILMN", "Illumina, Inc."),
        ("INCY", "Incyte Corporation"),
        ("INFA", "Informatica Inc."),
        ("INGM", "Ingram Micro Holding Corporatio"),
        ("INGR", "Ingredion Incorporated"),
        ("INSP", "Inspire Medical Systems, Inc."),
        ("INTC", "Intel Corporation"),
        ("INTU", "Intuit Inc."),
        ("INVH", "Invitation Homes Inc."),
        ("IONS", "Ionis Pharmaceuticals, Inc."),
        ("IP", "International Paper Company"),
        ("IPG", "Interpublic Group of Companies,"),
        ("IPGP", "IPG Photonics Corporation"),
        ("IQV", "IQVIA Holdings, Inc."),
        ("IR", "Ingersoll Rand Inc."),
        ("IRDM", "Iridium Communications Inc"),
        ("IRM", "Iron Mountain Incorporated (Del"),
        ("ISRG", "Intuitive Surgical, Inc."),
        ("IT", "Gartner, Inc."),
        ("ITCI", "Intra-Cellular Therapies Inc."),
        ("ITRI", "Itron, Inc."),
        ("ITT", "ITT Inc."),
        ("ITW", "Illinois Tool Works Inc."),
        ("IVZ", "Invesco Ltd"),
        ("J", "Jacobs Solutions Inc."),
        ("JAZZ", "Jazz Pharmaceuticals plc"),
        ("JBHT", "J.B. Hunt Transport Services, I"),
        ("JBL", "Jabil Inc."),
        ("JCI", "Johnson Controls International "),
        ("JEF", "Jefferies Financial Group Inc."),
        ("JHG", "Janus Henderson Group plc"),
        ("JKHY", "Jack Henry & Associates, Inc."),
        ("JLL", "Jones Lang LaSalle Incorporated"),
        ("JNJ", "Johnson & Johnson"),
        ("JNPR", "Juniper Networks, Inc."),
        ("JPM", "JP Morgan Chase & Co."),
        ("JWN", "Nordstrom, Inc."),
        ("K", "Kellanova"),
        ("KBR", "KBR, Inc."),
        ("KD", "Kyndryl Holdings, Inc."),
        ("KDP", "Keurig Dr Pepper Inc."),
        ("KEX", "Kirby Corporation"),
        ("KEY", "KeyCorp"),
        ("KEYS", "Keysight Technologies Inc."),
        ("KHC", "The Kraft Heinz Company"),
        ("KIM", "Kimco Realty Corporation (HC)"),
        ("KKR", "KKR & Co. Inc."),
        ("KLAC", "KLA Corporation"),
        ("KLIC", "Kulicke and Soffa Industries, I"),
        ("KMB", "Kimberly-Clark Corporation"),
        ("KMI", "Kinder Morgan, Inc."),
        ("KMPR", "Kemper Corporation"),
        ("KMX", "CarMax Inc"),
        ("KN", "Knowles Corporation"),
        ("KNSL", "Kinsale Capital Group, Inc."),
        ("KNX", "Knight-Swift Transportation Hol"),
        ("KO", "Coca-Cola Company (The)"),
        ("KR", "Kroger Company (The)"),
        ("KRC", "Kilroy Realty Corporation"),
        ("KSS", "Kohl's Corporation"),
        ("KVUE", "Kenvue Inc."),
        ("L", "Loews Corporation"),
        ("LAD", "Lithia Motors, Inc."),
        ("LAMR", "Lamar Advertising Company"),
        ("LAZ", "Lazard, Inc."),
        ("LBRDA", "Liberty Broadband Corporation"),
        ("LBRDK", "Liberty Broadband Corporation"),
        ("LBTYA", "Liberty Global Ltd."),
        ("LBTYK", "Liberty Global Ltd."),
        ("LCID", "Lucid Group, Inc."),
        ("LDOS", "Leidos Holdings, Inc."),
        ("LEA", "Lear Corporation"),
        ("LECO", "Lincoln Electric Holdings, Inc."),
        ("LEG", "Leggett & Platt, Incorporated"),
        ("LEN", "Lennar Corporation"),
        ("LFUS", "Littelfuse, Inc."),
        ("LH", "Labcorp Holdings Inc."),
        ("LHX", "L3Harris Technologies, Inc."),
        ("LII", "Lennox International, Inc."),
        ("LIN", "Linde plc"),
        ("LINE", "Lineage, Inc."),
        ("LITE", "Lumentum Holdings Inc."),
        ("LKQ", "LKQ Corporation"),
        ("LLY", "Eli Lilly and Company"),
        ("LLYVA", "Liberty Media Corporation - Ser"),
        ("LLYVK", "Liberty Media Corporation - Ser"),
        ("LMT", "Lockheed Martin Corporation"),
        ("LNC", "Lincoln National Corporation"),
        ("LNG", "Cheniere Energy, Inc."),
        ("LNT", "Alliant Energy Corporation"),
        ("LNW", "Light & Wonder, Inc."),
        ("LOAR", "Loar Holdings Inc."),
        ("LOPE", "Grand Canyon Education, Inc."),
        ("LOW", "Lowe's Companies, Inc."),
        ("LPLA", "LPL Financial Holdings Inc."),
        ("LPX", "Louisiana-Pacific Corporation"),
        ("LRCX", "Lam Research Corporation"),
        ("LSCC", "Lattice Semiconductor Corporati"),
        ("LSTR", "Landstar System, Inc."),
        ("LULU", "lululemon athletica inc."),
        ("LUV", "Southwest Airlines Company"),
        ("LVS", "Las Vegas Sands Corp."),
        ("LW", "Lamb Weston Holdings, Inc."),
        ("LYB", "LyondellBasell Industries NV"),
        ("LYFT", "Lyft, Inc."),
        ("LYV", "Live Nation Entertainment, Inc."),
        ("M", "Macy's Inc"),
        ("MA", "Mastercard Incorporated"),
        ("MAA", "Mid-America Apartment Communiti"),
        ("MAN", "ManpowerGroup"),
        ("MANH", "Manhattan Associates, Inc."),
        ("MAR", "Marriott International"),
        ("MARA", "MARA Holdings, Inc."),
        ("MAS", "Masco Corporation"),
        ("MASI", "Masimo Corporation"),
        ("MAT", "Mattel, Inc."),
        ("MCD", "McDonald's Corporation"),
        ("MCHP", "Microchip Technology Incorporat"),
        ("MCK", "McKesson Corporation"),
        ("MCO", "Moody's Corporation"),
        ("MDB", "MongoDB, Inc."),
        ("MDLZ", "Mondelez International, Inc."),
        ("MDT", "Medtronic plc."),
        ("MDU", "MDU Resources Group, Inc."),
        ("MEDP", "Medpace Holdings, Inc."),
        ("MET", "MetLife, Inc."),
        ("MGM", "MGM Resorts International"),
        ("MHK", "Mohawk Industries, Inc."),
        ("MIDD", "The Middleby Corporation"),
        ("MKC", "McCormick & Company, Incorporat"),
        ("MKL", "Markel Group Inc."),
        ("MKSI", "MKS Inc."),
        ("MKTX", "MarketAxess Holdings, Inc."),
        ("MLM", "Martin Marietta Materials, Inc."),
        ("MMC", "Marsh & McLennan Companies, Inc"),
        ("MMM", "3M Company"),
        ("MNST", "Monster Beverage Corporation"),
        ("MO", "Altria Group, Inc."),
        ("MOH", "Molina Healthcare Inc"),
        ("MORN", "Morningstar, Inc."),
        ("MOS", "Mosaic Company (The)"),
        ("MP", "MP Materials Corp."),
        ("MPC", "Marathon Petroleum Corporation"),
        ("MPW", "Medical Properties Trust, Inc."),
        ("MPWR", "Monolithic Power Systems, Inc."),
        ("MRK", "Merck & Company, Inc."),
        ("MRNA", "Moderna, Inc."),
        ("MRVL", "Marvell Technology, Inc."),
        ("MS", "Morgan Stanley"),
        ("MSA", "MSA Safety Incorporated"),
        ("MSCI", "MSCI Inc."),
        ("MSGS", "Madison Square Garden Sports Co"),
        ("MSI", "Motorola Solutions, Inc."),
        ("MSM", "MSC Industrial Direct Company, "),
        ("MSTR", "MicroStrategy Incorporated"),
        ("MTB", "M&T Bank Corporation"),
        ("MTCH", "Match Group, Inc."),
        ("MTD", "Mettler-Toledo International, I"),
        ("MTDR", "Matador Resources Company"),
        ("MTG", "MGIC Investment Corporation"),
        ("MTN", "Vail Resorts, Inc."),
        ("MTSI", "MACOM Technology Solutions Hold"),
        ("MTZ", "MasTec, Inc."),
        ("MU", "Micron Technology, Inc."),
        ("MUSA", "Murphy USA Inc."),
        ("MXL", "MaxLinear, Inc"),
        ("NABL", "N-able, Inc."),
        ("NBIX", "Neurocrine Biosciences, Inc."),
        ("NCLH", "Norwegian Cruise Line Holdings "),
        ("NCNO", "nCino, Inc."),
        ("NDAQ", "Nasdaq, Inc."),
        ("NDSN", "Nordson Corporation"),
        ("NEE", "NextEra Energy, Inc."),
        ("NEM", "Newmont Corporation"),
        ("NET", "Cloudflare, Inc."),
        ("NEU", "NewMarket Corp"),
        ("NFE", "New Fortress Energy Inc."),
        ("NFG", "National Fuel Gas Company"),
        ("NFLX", "Netflix, Inc."),
        ("NI", "NiSource Inc"),
        ("NKE", "Nike, Inc."),
        ("NLY", "Annaly Capital Management Inc."),
        ("NNN", "NNN REIT, Inc."),
        ("NOC", "Northrop Grumman Corporation"),
        ("NOV", "NOV Inc."),
        ("NOVT", "Novanta Inc."),
        ("NOW", "ServiceNow, Inc."),
        ("NRG", "NRG Energy, Inc."),
        ("NSA", "National Storage Affiliates Tru"),
        ("NSC", "Norfolk Southern Corporation"),
        ("NTAP", "NetApp, Inc."),
        ("NTCT", "NetScout Systems, Inc."),
        ("NTNX", "Nutanix, Inc."),
        ("NTRA", "Natera, Inc."),
        ("NTRS", "Northern Trust Corporation"),
        ("NU", "Nu Holdings Ltd."),
        ("NUE", "Nucor Corporation"),
        ("NVDA", "NVIDIA Corporation"),
        ("NVR", "NVR, Inc."),
        ("NVST", "Envista Holdings Corporation"),
        ("NVT", "nVent Electric plc"),
        ("NWL", "Newell Brands Inc."),
        ("NWS", "News Corporation"),
        ("NWSA", "News Corporation"),
        ("NXPI", "NXP Semiconductors N.V."),
        ("NXST", "Nexstar Media Group, Inc."),
        ("NYT", "New York Times Company (The)"),
        ("O", "Realty Income Corporation"),
        ("OC", "Owens Corning Inc"),
        ("ODFL", "Old Dominion Freight Line, Inc."),
        ("OGE", "OGE Energy Corp"),
        ("OGN", "Organon & Co."),
        ("OHI", "Omega Healthcare Investors, Inc"),
        ("OKE", "ONEOK, Inc."),
        ("OKTA", "Okta, Inc."),
        ("OLED", "Universal Display Corporation"),
        ("OLLI", "Ollie's Bargain Outlet Holdings"),
        ("OLN", "Olin Corporation"),
        ("OMC", "Omnicom Group Inc."),
        ("OMF", "OneMain Holdings, Inc."),
        ("ON", "ON Semiconductor Corporation"),
        ("ONTO", "Onto Innovation Inc."),
        ("ORCL", "Oracle Corporation"),
        ("ORI", "Old Republic International Corp"),
        ("ORLY", "O'Reilly Automotive, Inc."),
        ("OSIS", "OSI Systems, Inc."),
        ("OSK", "Oshkosh Corporation (Holding Co"),
        ("OTIS", "Otis Worldwide Corporation"),
        ("OVV", "Ovintiv Inc. (DE)"),
        ("OWL", "Blue Owl Capital Inc."),
        ("OXY", "Occidental Petroleum Corporatio"),
        ("OZK", "Bank OZK"),
        ("PAG", "Penske Automotive Group, Inc."),
        ("PANW", "Palo Alto Networks, Inc."),
        ("PARA", "Paramount Global"),
        ("PARAA", "Paramount Global"),
        ("PATH", "UiPath, Inc."),
        ("PAYC", "Paycom Software, Inc."),
        ("PAYX", "Paychex, Inc."),
        ("PB", "Prosperity Bancshares, Inc."),
        ("PCAR", "PACCAR Inc."),
        ("PCG", "Pacific Gas & Electric Co."),
        ("PCOR", "Procore Technologies, Inc."),
        ("PCTY", "Paylocity Holding Corporation"),
        ("PEG", "Public Service Enterprise Group"),
        ("PEGA", "Pegasystems Inc."),
        ("PEN", "Penumbra, Inc."),
        ("PENN", "PENN Entertainment, Inc."),
        ("PEP", "Pepsico, Inc."),
        ("PFE", "Pfizer, Inc."),
        ("PFG", "Principal Financial Group Inc"),
        ("PFGC", "Performance Food Group Company"),
        ("PG", "Procter & Gamble Company (The)"),
        ("PGR", "Progressive Corporation (The)"),
        ("PH", "Parker-Hannifin Corporation"),
        ("PHM", "PulteGroup, Inc."),
        ("PI", "Impinj, Inc."),
        ("PII", "Polaris Inc."),
        ("PINC", "Premier, Inc."),
        ("PINS", "Pinterest, Inc."),
        ("PK", "Park Hotels & Resorts Inc."),
        ("PKG", "Packaging Corporation of Americ"),
        ("PLAB", "Photronics, Inc."),
        ("PLD", "Prologis, Inc."),
        ("PLNT", "Planet Fitness, Inc."),
        ("PLTK", "Playtika Holding Corp."),
        ("PLTR", "Palantir Technologies Inc."),
        ("PLUS", "ePlus inc."),
        ("PLXS", "Plexus Corp."),
        ("PM", "Philip Morris International Inc"),
        ("PNC", "PNC Financial Services Group, I"),
        ("PNFP", "Pinnacle Financial Partners, In"),
        ("PNR", "Pentair plc."),
        ("PNW", "Pinnacle West Capital Corporati"),
        ("PODD", "Insulet Corporation"),
        ("POOL", "Pool Corporation"),
        ("POST", "Post Holdings, Inc."),
        ("POWI", "Power Integrations, Inc."),
        ("PPC", "Pilgrim's Pride Corporation"),
        ("PPG", "PPG Industries, Inc."),
        ("PPL", "PPL Corporation"),
        ("PR", "Permian Resources Corporation"),
        ("PRGO", "Perrigo Company plc"),
        ("PRGS", "Progress Software Corporation"),
        ("PRI", "Primerica, Inc."),
        ("PRU", "Prudential Financial, Inc."),
        ("PSA", "Public Storage"),
        ("PSN", "Parsons Corporation"),
        ("PSTG", "Pure Storage, Inc."),
        ("PSX", "Phillips 66"),
        ("PTC", "PTC Inc."),
        ("PVH", "PVH Corp."),
        ("PWR", "Quanta Services, Inc."),
        ("PYCR", "Paycor HCM, Inc."),
        ("PYPL", "PayPal Holdings, Inc."),
        ("QCOM", "QUALCOMM Incorporated"),
        ("QDEL", "QuidelOrtho Corporation"),
        ("QGEN", "Qiagen N.V."),
        ("QLYS", "Qualys, Inc."),
        ("QRVO", "Qorvo, Inc."),
        ("QS", "QuantumScape Corporation"),
        ("R", "Ryder System, Inc."),
        ("RAMP", "LiveRamp Holdings, Inc."),
        ("RARE", "Ultragenyx Pharmaceutical Inc."),
        ("RBA", "RB Global, Inc."),
        ("RBC", "RBC Bearings Incorporated"),
        ("RBLX", "Roblox Corporation"),
        ("RCL", "Royal Caribbean Cruises Ltd."),
        ("REG", "Regency Centers Corporation"),
        ("REGN", "Regeneron Pharmaceuticals, Inc."),
        ("REXR", "Rexford Industrial Realty, Inc."),
        ("REYN", "Reynolds Consumer Products Inc."),
        ("RF", "Regions Financial Corporation"),
        ("RGA", "Reinsurance Group of America, I"),
        ("RGEN", "Repligen Corporation"),
        ("RGLD", "Royal Gold, Inc."),
        ("RH", "RH"),
        ("RHI", "Robert Half Inc."),
        ("RITM", "Rithm Capital Corp."),
        ("RIVN", "Rivian Automotive, Inc."),
        ("RJF", "Raymond James Financial, Inc."),
        ("RKT", "Rocket Companies, Inc."),
        ("RL", "Ralph Lauren Corporation"),
        ("RLI", "RLI Corp."),
        ("RMBS", "Rambus, Inc."),
        ("RMD", "ResMed Inc."),
        ("RNG", "Ringcentral, Inc."),
        ("RNR", "RenaissanceRe Holdings Ltd."),
        ("ROIV", "Roivant Sciences Ltd."),
        ("ROK", "Rockwell Automation, Inc."),
        ("ROKU", "Roku, Inc."),
        ("ROL", "Rollins, Inc."),
        ("ROP", "Roper Technologies, Inc."),
        ("ROST", "Ross Stores, Inc."),
        ("RPM", "RPM International Inc."),
        ("RPRX", "Royalty Pharma plc"),
        ("RRC", "Range Resources Corporation"),
        ("RRX", "Regal Rexnord Corporation"),
        ("RS", "Reliance, Inc."),
        ("RSG", "Republic Services, Inc."),
        ("RTX", "RTX Corporation"),
        ("RVTY", "Revvity, Inc."),
        ("RYAN", "Ryan Specialty Holdings, Inc."),
        ("RYN", "Rayonier Inc. REIT"),
        ("S", "SentinelOne, Inc."),
        ("SAIA", "Saia, Inc."),
        ("SAIC", "Science Applications Internatio"),
        ("SAM", "Boston Beer Company, Inc. (The)"),
        ("SANM", "Sanmina Corporation"),
        ("SARO", "StandardAero, Inc."),
        ("SBAC", "SBA Communications Corporation"),
        ("SBUX", "Starbucks Corporation"),
        ("SCCO", "Southern Copper Corporation"),
        ("SCHW", "Charles Schwab Corporation (The"),
        ("SCI", "Service Corporation Internation"),
        ("SCSC", "ScanSource, Inc."),
        ("SEB", "Seaboard Corporation"),
        ("SEDG", "SolarEdge Technologies, Inc."),
        ("SEE", "Sealed Air Corporation"),
        ("SEG", "Seaport Entertainment Group Inc"),
        ("SEIC", "SEI Investments Company"),
        ("SF", "Stifel Financial Corporation"),
        ("SHC", "Sotera Health Company"),
        ("SHW", "Sherwin-Williams Company (The)"),
        ("SIRI", "SiriusXM Holdings Inc."),
        ("SITE", "SiteOne Landscape Supply, Inc."),
        ("SITM", "SiTime Corporation"),
        ("SJM", "The J.M. Smucker Company"),
        ("SKX", "Skechers U.S.A., Inc."),
        ("SLAB", "Silicon Laboratories, Inc."),
        ("SLB", "Schlumberger N.V."),
        ("SLGN", "Silgan Holdings Inc."),
        ("SLM", "SLM Corporation"),
        ("SMCI", "Super Micro Computer, Inc."),
        ("SMG", "Scotts Miracle-Gro Company (The"),
        ("SMTC", "Semtech Corporation"),
        ("SN", "SharkNinja, Inc."),
        ("SNA", "Snap-On Incorporated"),
        ("SNDR", "Schneider National, Inc."),
        ("SNOW", "Snowflake Inc."),
        ("SNPS", "Synopsys, Inc."),
        ("SNV", "Synovus Financial Corp."),
        ("SNX", "TD SYNNEX Corporation"),
        ("SO", "Southern Company (The)"),
        ("SOFI", "SoFi Technologies, Inc."),
        ("SOLV", "Solventum Corporation"),
        ("SON", "Sonoco Products Company"),
        ("SPB", "Spectrum Brands Holdings, Inc."),
        ("SPG", "Simon Property Group, Inc."),
        ("SPGI", "S&P Global Inc."),
        ("SPOT", "Spotify Technology S.A."),
        ("SPR", "Spirit Aerosystems Holdings, In"),
        ("SPSC", "SPS Commerce, Inc."),
        ("SRE", "DBA Sempra"),
        ("SRPT", "Sarepta Therapeutics, Inc."),
        ("SSD", "Simpson Manufacturing Company, "),
        ("SSNC", "SS&C Technologies Holdings, Inc"),
        ("ST", "Sensata Technologies Holding pl"),
        ("STAG", "Stag Industrial, Inc."),
        ("STE", "STERIS plc (Ireland)"),
        ("STLD", "Steel Dynamics, Inc."),
        ("STT", "State Street Corporation"),
        ("STWD", "STARWOOD PROPERTY TRUST, INC. S"),
        ("STX", "Seagate Technology Holdings PLC"),
        ("STZ", "Constellation Brands, Inc."),
        ("SUI", "Sun Communities, Inc."),
        ("SW", "Smurfit WestRock plc"),
        ("SWI", "SolarWinds Corporation"),
        ("SWK", "Stanley Black & Decker, Inc."),
        ("SWKS", "Skyworks Solutions, Inc."),
        ("SYF", "Synchrony Financial"),
        ("SYK", "Stryker Corporation"),
        ("SYNA", "Synaptics Incorporated"),
        ("SYY", "Sysco Corporation"),
        ("T", "AT&T Inc."),
        ("TAP", "Molson Coors Beverage Company"),
        ("TDC", "Teradata Corporation"),
        ("TDG", "Transdigm Group Incorporated"),
        ("TDY", "Teledyne Technologies Incorpora"),
        ("TEAM", "Atlassian Corporation"),
        ("TECH", "Bio-Techne Corp"),
        ("TEL", "TE Connectivity plc"),
        ("TER", "Teradyne, Inc."),
        ("TFC", "Truist Financial Corporation"),
        ("TFSL", "TFS Financial Corporation"),
        ("TFX", "Teleflex Incorporated"),
        ("TGT", "Target Corporation"),
        ("THC", "Tenet Healthcare Corporation"),
        ("THG", "Hanover Insurance Group Inc"),
        ("THO", "Thor Industries, Inc."),
        ("TJX", "TJX Companies, Inc. (The)"),
        ("TKO", "TKO Group Holdings, Inc."),
        ("TKR", "Timken Company (The)"),
        ("TMO", "Thermo Fisher Scientific Inc"),
        ("TMUS", "T-Mobile US, Inc."),
        ("TNL", "Travel   Leisure Co."),
        ("TOL", "Toll Brothers, Inc."),
        ("TOST", "Toast, Inc."),
        ("TPG", "TPG Inc."),
        ("TPL", "Texas Pacific Land Corporation"),
        ("TPR", "Tapestry, Inc."),
        ("TREX", "Trex Company, Inc."),
        ("TRGP", "Targa Resources, Inc."),
        ("TRIP", "TripAdvisor, Inc."),
        ("TRMB", "Trimble Inc."),
        ("TROW", "T. Rowe Price Group, Inc."),
        ("TRU", "TransUnion"),
        ("TRV", "The Travelers Companies, Inc."),
        ("TSCO", "Tractor Supply Company"),
        ("TSLA", "Tesla, Inc."),
        ("TSN", "Tyson Foods, Inc."),
        ("TT", "Trane Technologies plc"),
        ("TTC", "Toro Company (The)"),
        ("TTD", "The Trade Desk, Inc."),
        ("TTEK", "Tetra Tech, Inc."),
        ("TTMI", "TTM Technologies, Inc."),
        ("TTWO", "Take-Two Interactive Software, "),
        ("TW", "Tradeweb Markets Inc."),
        ("TWLO", "Twilio Inc."),
        ("TXG", "10x Genomics, Inc."),
        ("TXN", "Texas Instruments Incorporated"),
        ("TXRH", "Texas Roadhouse, Inc."),
        ("TXT", "Textron Inc."),
        ("TYL", "Tyler Technologies, Inc."),
        ("U", "Unity Software Inc."),
        ("UA", "Under Armour, Inc."),
        ("UAL", "United Airlines Holdings, Inc."),
        ("UBER", "Uber Technologies, Inc."),
        ("UCTT", "Ultra Clean Holdings, Inc."),
        ("UDR", "UDR, Inc."),
        ("UGI", "UGI Corporation"),
        ("UHAL", "U-Haul Holding Company"),
        ("UHS", "Universal Health Services, Inc."),
        ("UI", "Ubiquiti Inc."),
        ("ULTA", "Ulta Beauty, Inc."),
        ("UNH", "UnitedHealth Group Incorporated"),
        ("UNM", "Unum Group"),
        ("UNP", "Union Pacific Corporation"),
        ("UPS", "United Parcel Service, Inc."),
        ("URI", "United Rentals, Inc."),
        ("USB", "U.S. Bancorp"),
        ("USFD", "US Foods Holding Corp."),
        ("UTHR", "United Therapeutics Corporation"),
        ("UWMC", "UWM Holdings Corporation"),
        ("V", "Visa Inc."),
        ("VAC", "Marriott Vacations Worldwide Co"),
        ("VECO", "Veeco Instruments Inc."),
        ("VEEV", "Veeva Systems Inc."),
        ("VFC", "V.F. Corporation"),
        ("VIAV", "Viavi Solutions Inc."),
        ("VICI", "VICI Properties Inc."),
        ("VIRT", "Virtu Financial, Inc."),
        ("VKTX", "Viking Therapeutics, Inc."),
        ("VLO", "Valero Energy Corporation"),
        ("VLTO", "Veralto Corp"),
        ("VMC", "Vulcan Materials Company (Holdi"),
        ("VMI", "Valmont Industries, Inc."),
        ("VNO", "Vornado Realty Trust"),
        ("VNOM", "Viper Energy, Inc."),
        ("VNT", "Vontier Corporation"),
        ("VOYA", "Voya Financial, Inc."),
        ("VRSK", "Verisk Analytics, Inc."),
        ("VRSN", "VeriSign, Inc."),
        ("VRT", "Vertiv Holdings, LLC"),
        ("VRTX", "Vertex Pharmaceuticals Incorpor"),
        ("VSAT", "ViaSat, Inc."),
        ("VSH", "Vishay Intertechnology, Inc."),
        ("VST", "Vistra Corp."),
        ("VSTS", "Vestis Corporation"),
        ("VTR", "Ventas, Inc."),
        ("VTRS", "Viatris Inc."),
        ("VVV", "Valvoline Inc."),
        ("VYX", "NCR Voyix Corporation"),
        ("VZ", "Verizon Communications Inc."),
        ("W", "Wayfair Inc."),
        ("WAB", "Westinghouse Air Brake Technolo"),
        ("WAL", "Western Alliance Bancorporation"),
        ("WAT", "Waters Corporation"),
        ("WBA", "Walgreens Boots Alliance, Inc."),
        ("WBD", "Warner Bros. Discovery, Inc. - "),
        ("WBS", "Webster Financial Corporation"),
        ("WCC", "WESCO International, Inc."),
        ("WDAY", "Workday, Inc."),
        ("WDC", "Western Digital Corporation"),
        ("WEC", "WEC Energy Group, Inc."),
        ("WELL", "Welltower Inc."),
        ("WEN", "Wendy's Company (The)"),
        ("WEX", "WEX Inc."),
        ("WFC", "Wells Fargo & Company"),
        ("WFRD", "Weatherford International plc"),
        ("WH", "Wyndham Hotels & Resorts, Inc."),
        ("WHR", "Whirlpool Corporation"),
        ("WING", "Wingstop Inc."),
        ("WLK", "Westlake Corporation"),
        ("WM", "Waste Management, Inc."),
        ("WMB", "Williams Companies, Inc. (The)"),
        ("WMS", "Advanced Drainage Systems, Inc."),
        ("WMT", "Walmart Inc."),
        ("WOLF", "Wolfspeed, Inc."),
        ("WPC", "W. P. Carey Inc. REIT"),
        ("WRB", "W.R. Berkley Corporation"),
        ("WSC", "WillScot Holdings Corporation"),
        ("WSM", "Williams-Sonoma, Inc."),
        ("WSO", "Watsco, Inc."),
        ("WST", "West Pharmaceutical Services, I"),
        ("WTFC", "Wintrust Financial Corporation"),
        ("WTM", "White Mountains Insurance Group"),
        ("WTRG", "Essential Utilities, Inc."),
        ("WTW", "Willis Towers Watson Public Lim"),
        ("WU", "Western Union Company (The)"),
        ("WWD", "Woodward, Inc."),
        ("WY", "Weyerhaeuser Company"),
        ("WYNN", "Wynn Resorts, Limited"),
        ("X", "United States Steel Corporation"),
        ("XEL", "Xcel Energy Inc."),
        ("XOM", "Exxon Mobil Corporation"),
        ("XP", "XP Inc."),
        ("XPO", "XPO, Inc."),
        ("XRAY", "DENTSPLY SIRONA Inc."),
        ("XRX", "Xerox Holdings Corporation"),
        ("XYL", "Xylem Inc."),
        ("YETI", "YETI Holdings, Inc."),
        ("YOU", "Clear Secure, Inc."),
        ("YUM", "Yum! Brands, Inc."),
        ("Z", "Zillow Group, Inc."),
        ("ZBH", "Zimmer Biomet Holdings, Inc."),
        ("ZBRA", "Zebra Technologies Corporation"),
        ("ZG", "Zillow Group, Inc."),
        ("ZI", "ZoomInfo Technologies Inc."),
        ("ZION", "Zions Bancorporation N.A."),
        ("ZM", "Zoom Communications, Inc."),
        ("ZS", "Zscaler, Inc."),
        ("ZTS", "Zoetis Inc."),

    ]

    for symbol, name in symbols:
        symbol_manager.add_symbol(symbol, name)
        print(f"Added symbol: {symbol} ({name})")


def list_active_symbols(symbol_manager):
    """List all active symbols."""
    symbols = symbol_manager.get_active_symbols()
    print("\nActive Symbols:")
    for symbol in symbols:
        info = symbol_manager.get_symbol_info(symbol)
        print(f"- {symbol}: {info['name'] if info else 'Unknown'}")


def deactivate_symbol(symbol_manager, symbol):
    """Deactivate a symbol."""
    symbol_manager.deactivate_symbol(symbol)
    print(f"Deactivated symbol: {symbol}")


def main():
    """Main flow to demonstrate SymbolManager database operations."""
    symbol_manager = SymbolManager()

    # Add sample symbols
    add_sample_symbols(symbol_manager)

    # List all active symbols
    list_active_symbols(symbol_manager)

    # Deactivate a symbol
    # deactivate_symbol(symbol_manager, "META")

    # List symbols again to see the change
    list_active_symbols(symbol_manager)


if __name__ == "__main__":
    main()
