database:
  host: localhost
  port: 5432
  name: trading_system
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool_size: 5
  max_overflow: 10
mlflow:
  tracking_uri: ${MLFLOW_TRACKING_URI:-http://localhost:5000}
  registry_uri: ${MLFLOW_REGISTRY_URI:-http://localhost:5000}
  experiment_name: pairs_trading
  artifact_root: ${MLFLOW_ARTIFACT_ROOT:-file:./mlruns}
model_registry:
  naming_pattern: pairs_trading_gru_garch_{sector}_{version}_{date}
  stages:
  - staging
  - production
  - archived
sectors:
  active:
  - Technology
  available:
  - Technology
  - Healthcare
  - "Financial Services"
  - "Basic Materials"
  - "Communication Services"
  - "Consumer Cyclical"
  - "Consumer Defensive"
  - Energy
  - Industrials
  - "Real Estate"
  - Utilities
performance_thresholds:
  f1_score_improvement: 0.02
  sharpe_ratio_improvement: 0.1
  max_drawdown_improvement: 0.01
  f1_score_minimum: 0.7
  sharpe_ratio_minimum: 1.0
variance_stability:
  # Original strict criteria (commented out)
  # arch_test_pvalue_threshold: 0.05
  # rolling_std_cv_threshold: 0.5
  # ljung_box_pvalue_threshold: 0.05
  
  # Current relaxed criteria (for testing/development)
  arch_test_pvalue_threshold: 1e-100  # Essentially ignore ARCH test
  rolling_std_cv_threshold: 2.0       # Allow higher volatility
  ljung_box_pvalue_threshold: 0.001   # More lenient autocorrelation test
  
  # Test parameters
  test_window: 30
  arch_lags: 5
  ljung_box_lags: 10
alpaca:
  api_key: ${ALPACA_API_KEY}
  secret_key: ${ALPACA_SECRET_KEY}
  base_url: https://paper-api.alpaca.markets
  data_url: https://data.alpaca.markets
websocket:
  mode: alpaca
  symbols:
  - AAPL
  - PDFS
  - ROG
  recycler:
    server_url: ws://localhost:8765
    replay_mode: loop
    replay_speed: 1.0
    date_range:
      start_date: '2025-06-23'
      end_date: '2025-06-30'
    symbols:
    - AAPL
    - PDFS
    - ROG
    loop_count: -1
    data_retention:
      recycled_data_days: 1
      auto_cleanup: true
app:
  environment: ${ENVIRONMENT}
  debug: ${DEBUG}
  log_level: ${LOG_LEVEL}
data_collection:
  interval_minutes: 60
  symbols:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - META
logging:
  level: INFO
  format: '{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}'
  log_dir: ${REPO_ROOT}/logs
  log_file: trading_system.log
  rotation: 500 MB
  retention: 10 days
  compression: zip
  max_age_days: 3
trading:
  default_currency: USD
  risk_free_rate: 0.02
  max_position_size: 0.1
  stop_loss_pct: 0.02
  take_profit_pct: 0.04
data:
  default_timeframe: 1d
  cache_dir: data/cache
  max_retries: 3
  timeout: 30
ml:
  random_state: 42
  test_size: 0.2
  validation_size: 0.1
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 100
  early_stopping_patience: 10
